### ISSUE TITLE
Virus Detection

### ISSUE THREAD

**Issue by andr3i1010** [wyatt8740/3DNUS#2]
My antivirus (Bitdefender) and browser (Opera GX) says it is a virus. Why?

**Comment by wyatt8740** [comment]
Probably because your antivirus sucks. I can promise you that I did not put any malware in this program.

I compiled these things years and years ago and no one had an issue until now.

I can't really check what is happening, though, since I don't use Windows at all, and I don't know what kind of virus the AV is classifying it as.

I don't really have much vested interest in fixing this personally, so I'd suggest you send the file to BitDefender as a false positive and see if they fix their stuff. If you're willing to trust a stranger on the internet, you can also try to pause your AV. Opera is probably feeding the file to your system-wide antivirus program. I know Firefox does something like that by default in Windows.

How to report a false positive:

https://www.bitdefender.com/consumer/support/answer/29358/
